### ISSUE TITLE
Everytime i play - wow mapper overrides the keys to open my bags

### ISSUE THREAD

**Issue by Wongfeihunter** [topher-au/WoWmapper#104]
The first time I installed wow mapper and console port, it worked like a charm.  Suddenly it started opening my bags no matter what button i press.  I've completely uninstalled EVERYTHING, including WOW, and reinstalled i all. I changed everything to default in each application, and it continues to be an issue. Any ideas?

I am using  a generic PC controller that is recognized as a Xbox controller.
Thanks

**Comment by seblindfors** [comment]
That behaviour is expected if you don't calibrate your controller in ConsolePort. Open the chat in-game and use the command /cp recalibrate and follow the instructions.

**Comment by thiagomaia971** [comment]
Same problem and not solved..

**Comment by saltypeppah** [comment]
I solved the problem, in a jerry rig kinda way. Turns out that console port makes your backpack become Shift-B instead of B. Not sure why it happened to me or possibly you. My solution was to turn my backpack and bag bindings off install an addon that opens all bags at once, then map Backpack back to B and then B to where I choose. But I still sit at the computer since I am still working out the kinks in the playability of the addon.
