### ISSUE TITLE
Auto walk/run

### ISSUE THREAD

**Issue by BanditBanditBandit** [topher-au/WoWmapper#40]
I have found an issue with the switching of walking and running, if you change the bindings of walk to shift / and put autorun to / then it will constantly make you start autowalking forward when you are inside the threshhold. Would it be possible to memory read the bindings for toggling walk/run?

**Comment by topher-au** [comment]
WoWmapper is supposed to override the keybind when ConsolePort is active, that's probably what's causing the issue. There's no way for me to know which button is actually bound to toggle run, so that's how we have made it work. If it's causing you significant trouble you may need to disable the feature.
